### ISSUE TITLE
OpenGL Object Destructors??

### ISSUE THREAD

**Issue by PixelRifts** [ambrosiogabe/CDungeonCrawler#4]
This is more of a question, but should there not be a destructor for VAOs VBOs and FBOs?

**Comment by ambrosiogabe** [comment]
There definitely should, when I first start a project I usually don't worry about that stuff, but it's definitely at a point where I should be destroying them. I'll fix this up in the next push 👍

**Comment by ambrosiogabe** [comment]
I'm reopening this, because I still haven't gotten it done and I don't want to forget about it :)

**Comment by PixelRifts** [comment]
Ok.

**Comment by ambrosiogabe** [comment]
Finally got around to implementing this, no memory leaks anymore :)
