### ISSUE TITLE
Not an Issue but just to ask permission

### ISSUE THREAD

**Issue by PixelRifts** [ambrosiogabe/CDungeonCrawler#5]
I may find time today and tomorrow to add multiple styles(colour schemes) to the project. If I should do this please reply and of course close the issue. (Also specify If you want me to comment the code) Thanks in advance. :)

**Comment by PixelRifts** [comment]
I am asking this because if you were planning to do this, I should not impede on it. lol

**Comment by ambrosiogabe** [comment]
That would be awesome! I was going to ask in my video if people wanted to make custom themes that I could use as part of customizing the engine. If you want you could create a folder called styles in the JadeEditor folder and put the complete styles there. I'll eventually make it a default search path for any themes :)

**Comment by PixelRifts** [comment]
Yeah, but I was also going to include the selecting of the themes. That was what I was asking.:D

**Comment by ambrosiogabe** [comment]
Yeah I'm ok with that too, it would make it easier for me in the long run 🙂. The code for initialization is a bit all over the place, so if you have any issues feel free to just respond to this thread. I usually work till around 4 PM CST, but after that I'll be checking github and everything

**Comment by PixelRifts** [comment]
OK! Should I close this issue or leave it open?

**Comment by ambrosiogabe** [comment]
We can close this for now and reopen if anything comes up regarding this. Thanks again for the help!

**Comment by PixelRifts** [comment]
Is the latest commit for this repo working? I got the error
```
mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in CommandHistory.obj
```

**Comment by PixelRifts** [comment]
(while trying to run the engine...)
btw 4 PM pst is 2:30 AM for me so if you respond, I can only check it in the morning @ about 9-10

**Comment by ambrosiogabe** [comment]
Can you try deleting your bin folders? You'll have to delete it in the root of the project and then go into every folder in the JadeEngine/vendor folders and delete those bin folders also

**Comment by PixelRifts** [comment]
Ill try

**Comment by ambrosiogabe** [comment]
All of them except for jadeEngine/vendor/monoVendor/bin if you do delete that one on accident you can just do a git pull. But I believe it should build correctly after that

**Comment by PixelRifts** [comment]
Ok.
Mono vendor does not have a bin folder though

**Comment by ambrosiogabe** [comment]
Ok, you may want to make sure you do a git pull then and make sure your up to date. If so it shouldn't matter if it has a bin folder or not. Also make sure you run build.bat before you launch visual studio again

**Comment by PixelRifts** [comment]
Here's the source of the problem I guess,
```
4>cl : command line warning D9025: overriding '/MT' with '/MTd'
```
Ill try what you say in the above comment 2hrs later i guess cause I have to go out now.

**Comment by ambrosiogabe** [comment]
The whole reason you're getting that error is because I switched the engine to a DLL and I had to switch the CRT to the DLL version. However visual studio won't automatically rebuild all the projects, so it will try to use the static library CRT in some projects (like glfw and imgui) and the dll CRT in others, which is why it says MTd instead of MDd. And you're good, sorry I responded so late, us being in different timezones is kind of hard Haha. But I'll keep an eye out on this thread

**Comment by PixelRifts** [comment]
Yeah IKR Ill be back.
Also if you can, could you list which projects are compiled statically and which into dlls? I may be able to fix it that way too.

**Comment by ambrosiogabe** [comment]
Definitely I'll also respond to this with the projects that are static and the ones that are dynamic

**Comment by ambrosiogabe** [comment]
Ok so, the dynamically built libraries are:
JadeEngine/vendor/GLFW
and that's it. However you should definitely delete these folders:
```
JadeEngine/vendor/GLFW/bin
JadeEngine/vendor/GLFW/bin-int

JadeEngine/vendor/glad/bin
JadeEngine/vendor/glad/bin-int

JadeEngine/vendor/box2DVendor/bin
JadeEngine/vendor/box2DVendor/bin-int

JadeEngine/vendor/imguiVendor/bin
JadeEngine/vendor/imguiVendor/bin-int
```
Because I had to switch all of them to be MDd instead of MTd, and if you delete the bin's it should force a rebuild on Visual Studio's part. It will take a few minutes longer, but I believe that should solve it. I also edited the premake file to remove monoVendor since it is not working correctly atm. 
So make sure to pull one more time and run `build.bat` one more time and that should be good.

**Comment by PixelRifts** [comment]
Im back. :D

**Comment by PixelRifts** [comment]
That didn't work. :(

**Comment by PixelRifts** [comment]
I may have found the issue. Ill write it when I wake up as it is very late rn

**Comment by ambrosiogabe** [comment]
Ok, so it turns out I had forgotten to push the updates to all the submodules that I had forked. Sorry about that! I figured it out after doing a fresh clone and I got the same issue. Now, if you update all your submodules and pull from origin/master again, you should have no issues building. Let me know if it persists :)

**Comment by PixelRifts** [comment]
Great thanks for the help!

**Comment by PixelRifts** [comment]
This repo takes ages to clone 😭

**Comment by PixelRifts** [comment]
In the Style json, what does AccentDark1 do?

**Comment by ambrosiogabe** [comment]
I cant remember off the top of my head, but I believe it's for when you hover over the menu buttons. It's possible that I did end up removing it though and not using it, but left it in the styles...

**Comment by PixelRifts** [comment]
Yeah it seems to not do anything

**Comment by ambrosiogabe** [comment]
Yeah it probably doesn't, I'll look into it in a bit though and double check

**Comment by PixelRifts** [comment]
k

**Comment by PixelRifts** [comment]
oceanic theme if you want to try it out!
https://gist.github.com/PixelRifts/eed74ed72c94dfe777b1e8d1a1b6d549

**Comment by ambrosiogabe** [comment]
I like it! And I realized that AccentDark1 is supposed to be the color of the menu buttons on hover, it looks like I was just missing the line of code to do that. If you change line 381 of ImGuiLayer.cpp to use s_AccentDark1, then you should see the results :)

**Comment by PixelRifts** [comment]
Ok!

**Comment by PixelRifts** [comment]
Wait though it already does s_AccentDark1 is already being used by line 381
I just did not notice what it did.

**Comment by ambrosiogabe** [comment]
Sorry line 380 and 381 should be s_AccentDark1. 
```c++
		colors[ImGuiCol_MenuBarButtonBgHover] = From(Settings::EditorStyle::s_AccentDark1);
		colors[ImGuiCol_MenuBarButtonBgActive] = From(Settings::EditorStyle::s_AccentDark1);
```
I guess today is just not my day haha

**Comment by PixelRifts** [comment]
+btw the json file that is loaded cannot contain comments for some reason

**Comment by ambrosiogabe** [comment]
Yea that's documented here: https://github.com/nlohmann/json/issues/376 for the library I'm using. It looks like they decided not to support it because it's not an official requirement of JSON, and they didn't think it would be a good idea for the library since it's primarily supposed to be used for serialization/deserialization, because then they would have to preserve the comments during parsing and everything. I eventually want to remove the need to manually edit the json files completely though which should help out in that regard :)

**Comment by PixelRifts** [comment]
BTW the premake5.lua has an error
In the postBuildCommands line 97, when you copy the dll, the directory to copy the dll contains the dll name. So the build and run fails. Ive fixed it in my fork but I am informing you just in case :)
Edit: Fixed Terrible Grammar

**Comment by ambrosiogabe** [comment]
Thanks for letting me know! I feel like there has to be a better solution to copying the dll's around too, I just haven't looked into it yet. The way I'm doing it now just feels wrong haha

**Comment by PixelRifts** [comment]
https://gist.github.com/PixelRifts/75456e0779e3cb6b433d4852f7d37779
Uranium Theme

**Comment by ambrosiogabe** [comment]
Nice! Thanks Nikhil, I'll be able to ship a bunch of themes with the engine now when it goes out to the testing phase :D

**Comment by PixelRifts** [comment]
Is there a helper function anywhere that can get all files in a directory(It is in form of a JPath)

**Comment by ambrosiogabe** [comment]
Yep, it's in Jade/file/IFile.h
```c++
static std::vector<JPath> GetFilesInDir(const JPath& directory)
```

For File System stuff, check out the file/IFile.h and file/IFileDialog.h for helpful functions :)

**Comment by PixelRifts** [comment]
I did remember seeing it somewhere but I just forgot where. :)

**Comment by PixelRifts** [comment]
I have created a styles folder in JadeEditor Project. Is there a static variable to target it? Like s_EngineAssetsPath in Settings::General

**Comment by ambrosiogabe** [comment]
There is no path to target the JadeEditor/styles directory. You can create it if you would like though, inside JadeEditor/util/Settings.h there are all the editor related settings. You can create a new variable inside the EditorStyle class, or create a new class if you think that would be a better approach.

**Comment by PixelRifts** [comment]
I was asking about the JadeEditor directory itself :)

**Comment by ambrosiogabe** [comment]
Gotcha, I thought I might have misunderstood that haha, there is no static variable that links to that either. I know I said you should create the styles directory in the JadeEditor directory, but if you feel like it may work better being stored in the default s_EngineAssetsPath, feel free to place it there instead. And if you do need to create more variables you can make them at your discretion. Once you create a pull request, I'll look through the code and let you know if there are any alternative ways to do things :) 

This is definitely making me think about documentation which is probably going to be a next step in the project after scripting is sufficiently supported. I think I'm going to use Doxygen and come up with some local files for now, and eventually make a website
